name: Build and Publish Resume PDF

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create folder for publishing pages
        run: |
          mkdir publish-pages

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume/resume.tex

      - name: Move PDF into publishing folder
        run: |
          mv resume.pdf publish-pages/

      - name: Upload to pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: publish-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
